#define _WIN32_WINNT 0x0601
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <algorithm>
#include <random>
#include <iomanip>
#include <thread>
#include <mutex>
#pragma comment(lib, "Ws2_32.lib")
namespace fs=std::filesystem;
static std::mutex logMutex;
static std::string enc(const std::string&s){std::ostringstream o;for(unsigned char c:s){if(isalnum(c)||c=='-'||c=='_'||c=='.'||c=='~'||c=='/')o<<c;else o<<'%'<<std::uppercase<<std::hex<<std::setw(2)<<std::setfill('0')<<(int)c<<std::nouppercase<<std::dec;}return o.str();}
static std::string dec(const std::string&s){std::string o;for(size_t i=0;i<s.size();i++){if(s[i]=='%'&&i+2<s.size()){try{o+=(char)std::stoi(s.substr(i+1,2),nullptr,16);i+=2;}catch(...){o+=s[i];}}else o+=s[i]=='+'?' ':s[i];}return o;}
static std::string esc(const std::string&s){std::string o;for(char c:s){if(c=='&')o+="&amp;";else if(c=='<')o+="&lt;";else if(c=='>')o+="&gt;";else if(c=='\"')o+="&quot;";else o+=c;}return o;}
static bool sendAll(SOCKET s,const char*p,size_t n){while(n){int k=send(s,p,(int)std::min<size_t>(n,1<<20),0);if(k<=0)return false;p+=k;n-=k;}return true;}
static void reply(SOCKET s,int code,const std::string&type,const std::string&body){std::string status=code==200?"OK":code==201?"Created":code==404?"Not Found":code==413?"Payload Too Large":"Bad Request";std::ostringstream h;h<<"HTTP/1.1 "<<code<<" "<<status<<"\r\nContent-Type: "<<type<<"\r\nContent-Length: "<<body.size()<<"\r\nConnection: close\r\nCache-Control: no-store\r\n\r\n";auto x=h.str();sendAll(s,x.data(),x.size());sendAll(s,body.data(),body.size());}
static fs::path safe(const fs::path&root,std::string rel){std::replace(rel.begin(),rel.end(),'\\','/');auto p=(root/fs::u8path(rel)).lexically_normal();auto r=root.generic_wstring(),c=fs::absolute(p).lexically_normal().generic_wstring();if(c.size()<r.size()||_wcsnicmp(c.c_str(),r.c_str(),r.size())|| (c.size()>r.size()&&c[r.size()]!=L'/'))throw std::runtime_error("Invalid path");return p;}
static void handle(SOCKET s,const fs::path&root,const std::string&token){char b[256*1024];std::string req;size_t end=std::string::npos;while((end=req.find("\r\n\r\n"))==std::string::npos&&req.size()<65536){int n=recv(s,b,sizeof(b),0);if(n<=0)return;req.append(b,n);}if(end==std::string::npos){reply(s,400,"text/plain","Bad request");return;}
 std::istringstream h(req.substr(0,end));std::string method,target,v,line;h>>method>>target>>v;size_t len=0;while(std::getline(h,line)){auto p=line.find(':');if(p!=std::string::npos){auto k=line.substr(0,p);std::transform(k.begin(),k.end(),k.begin(),::tolower);if(k=="content-length")try{len=std::stoull(line.substr(p+1));}catch(...){}}}
 auto q=target.find('?');std::string path=target.substr(0,q),query=q==std::string::npos?"":target.substr(q+1),pre="/t/"+token;if(path!=pre&&path.rfind(pre+"/",0)!=0){reply(s,404,"text/plain","Not found");return;}std::string rel=path.substr(pre.size());while(rel.size()&&rel[0]=='/')rel.erase(0,1);
 try{if(method=="POST"&&rel=="upload"){auto p=query.find("path=");if(p==std::string::npos){reply(s,400,"text/plain","Missing path");return;}auto a=p+5,z=query.find('&',a);auto name=dec(query.substr(a,z==std::string::npos?z:z-a));auto dest=safe(root,name);if(dest==root){reply(s,400,"text/plain","Invalid destination");return;}if(len>2ull*1024*1024*1024){reply(s,413,"text/plain","File exceeds 2 GiB");return;}fs::create_directories(dest.parent_path());std::ofstream out(dest,std::ios::binary|std::ios::trunc);if(!out){reply(s,400,"text/plain","Cannot write file");return;}size_t have=req.size()-(end+4),left=len;if(have){auto n=std::min(have,left);out.write(req.data()+end+4,(std::streamsize)n);if(!out)throw std::runtime_error("Disk write failed");left-=n;}while(left){int n=recv(s,b,(int)std::min<size_t>(sizeof(b),left),0);if(n<=0)throw std::runtime_error("Upload interrupted");out.write(b,n);if(!out)throw std::runtime_error("Disk write failed");left-=n;}out.close();if(!out)throw std::runtime_error("Disk write failed");{std::lock_guard<std::mutex>g(logMutex);std::cout<<"[업로드] "<<name<<" ("<<len<<" bytes)\n";}reply(s,201,"text/plain","Uploaded");return;}
 if(method!="GET"){reply(s,400,"text/plain","Unsupported");return;}auto f=safe(root,rel);if(fs::is_regular_file(f)){std::ifstream in(f,std::ios::binary);if(!in){reply(s,404,"text/plain","Cannot read file");return;}auto size=fs::file_size(f);std::string name=f.filename().u8string();std::ostringstream x;x<<"HTTP/1.1 200 OK\r\nContent-Type: application/octet-stream\r\nContent-Length: "<<size<<"\r\nContent-Disposition: attachment; filename*=UTF-8''"<<enc(name)<<"\r\nConnection: close\r\n\r\n";auto hs=x.str();if(!sendAll(s,hs.data(),hs.size()))return;while(in){in.read(b,sizeof(b));auto n=in.gcount();if(n>0&&!sendAll(s,b,(size_t)n))break;}return;}if(!fs::is_directory(f)){reply(s,404,"text/plain","Not found");return;}
 std::ostringstream o;o<<"<!doctype html><html lang=ko><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>ShareHub</title><style>body{font:16px system-ui;max-width:760px;margin:32px auto;padding:0 18px}.box{background:#f3f6fa;padding:18px;border-radius:12px}li{padding:8px 0}button{padding:10px;background:#155eef;color:white;border:0;border-radius:8px}</style><h1>ShareHub</h1><p>같은 Wi-Fi에서 파일을 빠르게 주고받습니다.</p><section class=box><form id=u><input id=f type=file multiple webkitdirectory><button>업로드</button><span id=s></span></form></section><h2>공유 폴더</h2><ul>";bool any=false;for(auto&e:fs::directory_iterator(f)){if(e.is_symlink())continue;any=true;std::string n=e.path().filename().u8string(),child=(rel.empty()?"":rel+"/")+n;o<<"<li><a href='/t/"<<token<<"/"<<enc(child)<<(e.is_directory()?"/":"")<<"'>"<<(e.is_directory()?"📁 ":"📄 ")<<esc(n)<<(e.is_directory()?"/":"")<<"</a>";if(e.is_regular_file())o<<" ("<<e.file_size()<<" bytes)";o<<"</li>";}if(!any)o<<"<li>아직 파일이 없습니다.</li>";o<<"</ul><script>const t='"<<token<<"',d='"<<esc(rel)<<"';document.querySelector('#u').onsubmit=async e=>{e.preventDefault();let fs=[...document.querySelector('#f').files],s=document.querySelector('#s'),i=0;for(let f of fs){let p=[d,f.webkitRelativePath||f.name].filter(Boolean).join('/');s.textContent=`업로드 ${i+1}/${fs.length}: ${f.name}`;let r=await fetch(`/t/${t}/upload?path=${encodeURIComponent(p)}`,{method:'POST',body:f});if(!r.ok){s.textContent='실패: '+await r.text();return}i++}s.textContent=`${i}개 완료`;location.reload()}</script></html>";reply(s,200,"text/html; charset=utf-8",o.str());}catch(const std::exception&e){reply(s,400,"text/plain; charset=utf-8",e.what());}}
static std::string token(){std::random_device d;const char*c="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_";std::string s;for(int i=0;i<22;i++)s+=c[d()%64];return s;}
static std::string ip(){char h[256]{};gethostname(h,sizeof(h));addrinfo a{},*r=nullptr;a.ai_family=AF_INET;if(getaddrinfo(h,nullptr,&a,&r))return"127.0.0.1";std::string out="127.0.0.1";for(auto p=r;p;p=p->ai_next){char x[INET_ADDRSTRLEN]{};inet_ntop(AF_INET,&((sockaddr_in*)p->ai_addr)->sin_addr,x,sizeof(x));if(std::string(x).rfind("127.",0)!=0){out=x;break;}}freeaddrinfo(r);return out;}
int main(int argc,char**argv){fs::path root=argc>1?fs::u8path(argv[1]):fs::path("Shared");int port=argc>2?std::stoi(argv[2]):8765;try{fs::create_directories(root);root=fs::canonical(root);}catch(...){std::cerr<<"공유 폴더를 열 수 없습니다.\n";return 1;}WSADATA w;if(WSAStartup(MAKEWORD(2,2),&w)){std::cerr<<"Winsock 초기화 실패\n";return 1;}SOCKET srv=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);int yes=1;setsockopt(srv,SOL_SOCKET,SO_REUSEADDR,(char*)&yes,sizeof(yes));sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons((u_short)port);a.sin_addr.s_addr=INADDR_ANY;if(bind(srv,(sockaddr*)&a,sizeof(a))||listen(srv,SOMAXCONN)){std::cerr<<"포트를 열 수 없습니다.\n";closesocket(srv);WSACleanup();return 1;}auto t=token();std::cout<<"ShareHub 실행 중\n공유 폴더: "<<root.u8string()<<"\niPhone Safari 주소: http://"<<ip()<<":"<<port<<"/t/"<<t<<"/\n끝나면 Ctrl+C로 종료하세요. 동시 전송을 지원합니다.\n";for(;;){SOCKET c=accept(srv,nullptr,nullptr);if(c==INVALID_SOCKET)break;int sz=4*1024*1024;setsockopt(c,SOL_SOCKET,SO_RCVBUF,(char*)&sz,sizeof(sz));setsockopt(c,SOL_SOCKET,SO_SNDBUF,(char*)&sz,sizeof(sz));std::thread([c,root,t]{handle(c,root,t);shutdown(c,SD_BOTH);closesocket(c);}).detach();}closesocket(srv);WSACleanup();}
